language: c 
script: ./configure --prefix=/home/travis/shalture --disable-nls --enable-ssl $CONFIGURE_WITH && make && make install
compiler:
  - gcc
  - clang 
matrix:
  fast_finish: true
  allow_failures:
    - env: CONFIGURE_WITH="--enable-contrib" 
env:
  - CONFIGURE_WITH=""
  - CONFIGURE_WITH="--with-perl"
  - CONFIGURE_WITH="--enable-contrib"
before_install:
  - git clone https://github.com/atheme/libmowgli-2 && cd libmowgli-2 && ./configure && make && sudo make install && cd ..
install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libperl-dev
